
export type Direction = 'LONG' | 'SHORT' | 'AUTO';
export type AgentOwner = 'USER' | 'SYSTEM';
export type AssetSymbol = 'BTC' | 'ETH' | 'SOL' | 'MON';

export interface Agent {
  id: string;
  owner: AgentOwner;
  minter: string; // Wallet address or 'Protocol'
  minterTwitter?: string; // Twitter handle of the minter
  name: string;
  bio: string;
  avatarSeed: string; // For generating unique avatar images
  direction: Direction;
  leverage: number;
  balance: number; // The collateral assigned to this agent
  pnl: number;
  pnlHistory: { time: string; value: number }[]; // 24h PnL history for charts
  wins: number;
  losses: number;
  status: 'IDLE' | 'ACTIVE' | 'LIQUIDATED';
  strategy: string; // Generated by AI
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'EXTREME'; // Based on leverage

  // Social Features
  twitterHandle?: string;
}

export interface MarketState {
  symbol: AssetSymbol;
  price: number;
  history: { time: string; price: number }[];
  trend: 'UP' | 'DOWN' | 'FLAT';
  lastChangePct: number;
}

export interface WalletState {
  address: string;
  balance: number; // Mock MON token
  totalPnl: number;
  // SocialFi / KOL Features
  referralCode?: string;
  referralEarnings: number;
  referralCount: number;
}

export interface BattleLog {
  id: string;
  timestamp: number;
  message: string;
  type: 'WIN' | 'LOSS' | 'LIQUIDATION' | 'MINT' | 'SOCIAL' | 'EXIT';
  amount?: number;
}

export interface LootEvent {
  amount: number;
  winner: Direction;
  timestamp: number;
}

export enum Tab {
  ARENA = 'ARENA',
  AGENTS = 'AGENTS',
  WALLET = 'WALLET',
  LEADERBOARD = 'LEADERBOARD'
}
